/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as DevenirAgentRouteImport } from './routes/devenir-agent'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OnboardingCommandeIdRouteImport } from './routes/onboarding.$commandeId'
import { Route as OnboardingSuccessCommandeIdRouteImport } from './routes/onboarding-success.$commandeId'
import { Route as AgentUpdatePasswordRouteImport } from './routes/agent.update-password'
import { Route as AgentRulesRouteImport } from './routes/agent.rules'
import { Route as AgentRevenueRouteImport } from './routes/agent.revenue'
import { Route as AgentMarketRouteImport } from './routes/agent.market'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AgentForgotPasswordRouteImport } from './routes/agent.forgot-password'
import { Route as AgentCasesRouteImport } from './routes/agent.cases'
import { Route as AgentIdRouteImport } from './routes/agent.$id'
import { Route as AdminStatistiquesRouteImport } from './routes/admin.statistiques'
import { Route as AdminParametresRouteImport } from './routes/admin.parametres'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminKanbanRouteImport } from './routes/admin.kanban'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCandidaturesRouteImport } from './routes/admin.candidatures'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as AcceptInvitationTokenRouteImport } from './routes/accept-invitation.$token'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicCronRemindersRouteImport } from './routes/api/public/cron-reminders'

const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirAgentRoute = DevenirAgentRouteImport.update({
  id: '/devenir-agent',
  path: '/devenir-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCommandeIdRoute = OnboardingCommandeIdRouteImport.update({
  id: '/onboarding/$commandeId',
  path: '/onboarding/$commandeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSuccessCommandeIdRoute =
  OnboardingSuccessCommandeIdRouteImport.update({
    id: '/onboarding-success/$commandeId',
    path: '/onboarding-success/$commandeId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AgentUpdatePasswordRoute = AgentUpdatePasswordRouteImport.update({
  id: '/agent/update-password',
  path: '/agent/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRulesRoute = AgentRulesRouteImport.update({
  id: '/agent/rules',
  path: '/agent/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRevenueRoute = AgentRevenueRouteImport.update({
  id: '/agent/revenue',
  path: '/agent/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentMarketRoute = AgentMarketRouteImport.update({
  id: '/agent/market',
  path: '/agent/market',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent/login',
  path: '/agent/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentForgotPasswordRoute = AgentForgotPasswordRouteImport.update({
  id: '/agent/forgot-password',
  path: '/agent/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentCasesRoute = AgentCasesRouteImport.update({
  id: '/agent/cases',
  path: '/agent/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIdRoute = AgentIdRouteImport.update({
  id: '/agent/$id',
  path: '/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStatistiquesRoute = AdminStatistiquesRouteImport.update({
  id: '/admin/statistiques',
  path: '/admin/statistiques',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/admin/parametres',
  path: '/admin/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKanbanRoute = AdminKanbanRouteImport.update({
  id: '/admin/kanban',
  path: '/admin/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidaturesRoute = AdminCandidaturesRouteImport.update({
  id: '/admin/candidatures',
  path: '/admin/candidatures',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/admin/agents',
  path: '/admin/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationTokenRoute = AcceptInvitationTokenRouteImport.update({
  id: '/accept-invitation/$token',
  path: '/accept-invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronRemindersRoute = ApiPublicCronRemindersRouteImport.update({
  id: '/api/public/cron-reminders',
  path: '/api/public/cron-reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/devenir-agent': typeof DevenirAgentRoute
  '/merci': typeof MerciRoute
  '/recrutement': typeof RecrutementRoute
  '/accept-invitation/$token': typeof AcceptInvitationTokenRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/candidatures': typeof AdminCandidaturesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/kanban': typeof AdminKanbanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/agent/$id': typeof AgentIdRoute
  '/agent/cases': typeof AgentCasesRoute
  '/agent/forgot-password': typeof AgentForgotPasswordRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/market': typeof AgentMarketRoute
  '/agent/revenue': typeof AgentRevenueRoute
  '/agent/rules': typeof AgentRulesRoute
  '/agent/update-password': typeof AgentUpdatePasswordRoute
  '/onboarding-success/$commandeId': typeof OnboardingSuccessCommandeIdRoute
  '/onboarding/$commandeId': typeof OnboardingCommandeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/api/public/cron-reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/devenir-agent': typeof DevenirAgentRoute
  '/merci': typeof MerciRoute
  '/recrutement': typeof RecrutementRoute
  '/accept-invitation/$token': typeof AcceptInvitationTokenRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/candidatures': typeof AdminCandidaturesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/kanban': typeof AdminKanbanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/agent/$id': typeof AgentIdRoute
  '/agent/cases': typeof AgentCasesRoute
  '/agent/forgot-password': typeof AgentForgotPasswordRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/market': typeof AgentMarketRoute
  '/agent/revenue': typeof AgentRevenueRoute
  '/agent/rules': typeof AgentRulesRoute
  '/agent/update-password': typeof AgentUpdatePasswordRoute
  '/onboarding-success/$commandeId': typeof OnboardingSuccessCommandeIdRoute
  '/onboarding/$commandeId': typeof OnboardingCommandeIdRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/api/public/cron-reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commander': typeof CommanderRoute
  '/devenir-agent': typeof DevenirAgentRoute
  '/merci': typeof MerciRoute
  '/recrutement': typeof RecrutementRoute
  '/accept-invitation/$token': typeof AcceptInvitationTokenRoute
  '/admin/$id': typeof AdminIdRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/candidatures': typeof AdminCandidaturesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/kanban': typeof AdminKanbanRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/parametres': typeof AdminParametresRoute
  '/admin/statistiques': typeof AdminStatistiquesRoute
  '/agent/$id': typeof AgentIdRoute
  '/agent/cases': typeof AgentCasesRoute
  '/agent/forgot-password': typeof AgentForgotPasswordRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/market': typeof AgentMarketRoute
  '/agent/revenue': typeof AgentRevenueRoute
  '/agent/rules': typeof AgentRulesRoute
  '/agent/update-password': typeof AgentUpdatePasswordRoute
  '/onboarding-success/$commandeId': typeof OnboardingSuccessCommandeIdRoute
  '/onboarding/$commandeId': typeof OnboardingCommandeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/api/public/cron-reminders': typeof ApiPublicCronRemindersRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commander'
    | '/devenir-agent'
    | '/merci'
    | '/recrutement'
    | '/accept-invitation/$token'
    | '/admin/$id'
    | '/admin/agents'
    | '/admin/candidatures'
    | '/admin/commissions'
    | '/admin/kanban'
    | '/admin/login'
    | '/admin/parametres'
    | '/admin/statistiques'
    | '/agent/$id'
    | '/agent/cases'
    | '/agent/forgot-password'
    | '/agent/login'
    | '/agent/market'
    | '/agent/revenue'
    | '/agent/rules'
    | '/agent/update-password'
    | '/onboarding-success/$commandeId'
    | '/onboarding/$commandeId'
    | '/admin/'
    | '/agent/'
    | '/api/public/cron-reminders'
    | '/api/public/stripe-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commander'
    | '/devenir-agent'
    | '/merci'
    | '/recrutement'
    | '/accept-invitation/$token'
    | '/admin/$id'
    | '/admin/agents'
    | '/admin/candidatures'
    | '/admin/commissions'
    | '/admin/kanban'
    | '/admin/login'
    | '/admin/parametres'
    | '/admin/statistiques'
    | '/agent/$id'
    | '/agent/cases'
    | '/agent/forgot-password'
    | '/agent/login'
    | '/agent/market'
    | '/agent/revenue'
    | '/agent/rules'
    | '/agent/update-password'
    | '/onboarding-success/$commandeId'
    | '/onboarding/$commandeId'
    | '/admin'
    | '/agent'
    | '/api/public/cron-reminders'
    | '/api/public/stripe-webhook'
  id:
    | '__root__'
    | '/'
    | '/commander'
    | '/devenir-agent'
    | '/merci'
    | '/recrutement'
    | '/accept-invitation/$token'
    | '/admin/$id'
    | '/admin/agents'
    | '/admin/candidatures'
    | '/admin/commissions'
    | '/admin/kanban'
    | '/admin/login'
    | '/admin/parametres'
    | '/admin/statistiques'
    | '/agent/$id'
    | '/agent/cases'
    | '/agent/forgot-password'
    | '/agent/login'
    | '/agent/market'
    | '/agent/revenue'
    | '/agent/rules'
    | '/agent/update-password'
    | '/onboarding-success/$commandeId'
    | '/onboarding/$commandeId'
    | '/admin/'
    | '/agent/'
    | '/api/public/cron-reminders'
    | '/api/public/stripe-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommanderRoute: typeof CommanderRoute
  DevenirAgentRoute: typeof DevenirAgentRoute
  MerciRoute: typeof MerciRoute
  RecrutementRoute: typeof RecrutementRoute
  AcceptInvitationTokenRoute: typeof AcceptInvitationTokenRoute
  AdminIdRoute: typeof AdminIdRoute
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminCandidaturesRoute: typeof AdminCandidaturesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminKanbanRoute: typeof AdminKanbanRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminStatistiquesRoute: typeof AdminStatistiquesRoute
  AgentIdRoute: typeof AgentIdRoute
  AgentCasesRoute: typeof AgentCasesRoute
  AgentForgotPasswordRoute: typeof AgentForgotPasswordRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentMarketRoute: typeof AgentMarketRoute
  AgentRevenueRoute: typeof AgentRevenueRoute
  AgentRulesRoute: typeof AgentRulesRoute
  AgentUpdatePasswordRoute: typeof AgentUpdatePasswordRoute
  OnboardingSuccessCommandeIdRoute: typeof OnboardingSuccessCommandeIdRoute
  OnboardingCommandeIdRoute: typeof OnboardingCommandeIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentIndexRoute: typeof AgentIndexRoute
  ApiPublicCronRemindersRoute: typeof ApiPublicCronRemindersRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-agent': {
      id: '/devenir-agent'
      path: '/devenir-agent'
      fullPath: '/devenir-agent'
      preLoaderRoute: typeof DevenirAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/$commandeId': {
      id: '/onboarding/$commandeId'
      path: '/onboarding/$commandeId'
      fullPath: '/onboarding/$commandeId'
      preLoaderRoute: typeof OnboardingCommandeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-success/$commandeId': {
      id: '/onboarding-success/$commandeId'
      path: '/onboarding-success/$commandeId'
      fullPath: '/onboarding-success/$commandeId'
      preLoaderRoute: typeof OnboardingSuccessCommandeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/update-password': {
      id: '/agent/update-password'
      path: '/agent/update-password'
      fullPath: '/agent/update-password'
      preLoaderRoute: typeof AgentUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/rules': {
      id: '/agent/rules'
      path: '/agent/rules'
      fullPath: '/agent/rules'
      preLoaderRoute: typeof AgentRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/revenue': {
      id: '/agent/revenue'
      path: '/agent/revenue'
      fullPath: '/agent/revenue'
      preLoaderRoute: typeof AgentRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/market': {
      id: '/agent/market'
      path: '/agent/market'
      fullPath: '/agent/market'
      preLoaderRoute: typeof AgentMarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/agent/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/forgot-password': {
      id: '/agent/forgot-password'
      path: '/agent/forgot-password'
      fullPath: '/agent/forgot-password'
      preLoaderRoute: typeof AgentForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/cases': {
      id: '/agent/cases'
      path: '/agent/cases'
      fullPath: '/agent/cases'
      preLoaderRoute: typeof AgentCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/$id': {
      id: '/agent/$id'
      path: '/agent/$id'
      fullPath: '/agent/$id'
      preLoaderRoute: typeof AgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/statistiques': {
      id: '/admin/statistiques'
      path: '/admin/statistiques'
      fullPath: '/admin/statistiques'
      preLoaderRoute: typeof AdminStatistiquesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/parametres': {
      id: '/admin/parametres'
      path: '/admin/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kanban': {
      id: '/admin/kanban'
      path: '/admin/kanban'
      fullPath: '/admin/kanban'
      preLoaderRoute: typeof AdminKanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidatures': {
      id: '/admin/candidatures'
      path: '/admin/candidatures'
      fullPath: '/admin/candidatures'
      preLoaderRoute: typeof AdminCandidaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/admin/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation/$token': {
      id: '/accept-invitation/$token'
      path: '/accept-invitation/$token'
      fullPath: '/accept-invitation/$token'
      preLoaderRoute: typeof AcceptInvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-reminders': {
      id: '/api/public/cron-reminders'
      path: '/api/public/cron-reminders'
      fullPath: '/api/public/cron-reminders'
      preLoaderRoute: typeof ApiPublicCronRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommanderRoute: CommanderRoute,
  DevenirAgentRoute: DevenirAgentRoute,
  MerciRoute: MerciRoute,
  RecrutementRoute: RecrutementRoute,
  AcceptInvitationTokenRoute: AcceptInvitationTokenRoute,
  AdminIdRoute: AdminIdRoute,
  AdminAgentsRoute: AdminAgentsRoute,
  AdminCandidaturesRoute: AdminCandidaturesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminKanbanRoute: AdminKanbanRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminStatistiquesRoute: AdminStatistiquesRoute,
  AgentIdRoute: AgentIdRoute,
  AgentCasesRoute: AgentCasesRoute,
  AgentForgotPasswordRoute: AgentForgotPasswordRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentMarketRoute: AgentMarketRoute,
  AgentRevenueRoute: AgentRevenueRoute,
  AgentRulesRoute: AgentRulesRoute,
  AgentUpdatePasswordRoute: AgentUpdatePasswordRoute,
  OnboardingSuccessCommandeIdRoute: OnboardingSuccessCommandeIdRoute,
  OnboardingCommandeIdRoute: OnboardingCommandeIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentIndexRoute: AgentIndexRoute,
  ApiPublicCronRemindersRoute: ApiPublicCronRemindersRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
